export const endpoints = {
  authLogin: "/api/auth/login",
  authRegister: "/api/auth/register",
  authProfile: "/api/auth/profile",
  authChangePassword: "/api/auth/change-password",
  authLogout: "/api/auth/logout",
  tournaments: "/api/tournaments",
  tournamentsPaged: "/api/tournaments/paged",
  tournamentsStats: "/api/tournaments/stats",
  tournamentTeams: (id: number) => `/api/tournaments/${id}/teams`,
  tournamentTeam: (id: number, teamId: number) => `/api/tournaments/${id}/teams/${teamId}`,
  tournamentBracket: (id: number) => `/api/tournaments/${id}/bracket/generate`,
  tournamentStandings: (id: number) => `/api/tournaments/${id}/standings`,
  matchScore: (id: number) => `/api/matches/${id}/score`,
  matchLinks: (id: number) => `/api/matches/${id}/links`,
  matchPlayers: (id: number) => `/api/matches/${id}/players`,
  matchPlayersAutofill: (id: number) => `/api/matches/${id}/players/autofill`,
  matchPlayer: (id: number, entryId: number) => `/api/matches/${id}/players/${entryId}`,
  teams: "/api/teams",
  teamsPaged: "/api/teams/paged",
  teamSummary: (id: number) => `/api/teams/${id}/summary`,
  players: "/api/players",
  playersPaged: "/api/players/paged",
  playersFull: "/api/players/full",
  playerProfile: (id: number) => `/api/players/${id}/profile`,
  playerMatches: (id: number) => `/api/players/${id}/matches`,
  matches: "/api/matches",
  matchesPaged: "/api/matches/paged",
  matchesScheduled: "/api/matches/scheduled",
  matchesLive: "/api/matches/live",
  matchesCompleted: "/api/matches/completed",
  users: "/api/users",
  usersPaged: "/api/users/paged",
  playersMe: "/api/players/me",
  playerApplications: (playerId: number, teamId: number) =>
    `/api/players/${playerId}/applications/${teamId}`,
  playerMembershipRequests: (playerId: number) =>
    `/api/players/${playerId}/membership-requests`,
  teamInvitations: (teamId: number, playerId: number) =>
    `/api/teams/${teamId}/invitations/${playerId}`,
  teamMembershipRequests: (teamId: number) =>
    `/api/teams/${teamId}/membership-requests`,
  membershipRequestAccept: (id: number) => `/api/membership-requests/${id}/accept`,
  membershipRequestDecline: (id: number) => `/api/membership-requests/${id}/decline`,
  membershipRequestCancel: (id: number) => `/api/membership-requests/${id}/cancel`,
  matchChallenges: "/api/match-challenges",
  matchChallengesPending: "/api/match-challenges/pending",
  matchChallengeAccept: (id: number) => `/api/match-challenges/${id}/accept`,
  matchChallengeDecline: (id: number) => `/api/match-challenges/${id}/decline`,
  matchChallengeCancel: (id: number) => `/api/match-challenges/${id}/cancel`,
  teamMatchChallenges: (teamId: number) => `/api/teams/${teamId}/match-challenges`,
  tournamentInvitations: (id: number) => `/api/tournaments/${id}/invitations`,
  tournamentInvite: (id: number, teamId: number) => `/api/tournaments/${id}/invitations/${teamId}`,
  tournamentApplication: (id: number, teamId: number) =>
    `/api/tournaments/${id}/applications/${teamId}`,
  teamTournamentInvitations: (teamId: number) => `/api/teams/${teamId}/tournament-invitations`,
  tournamentInvitationAccept: (id: number) => `/api/tournament-invitations/${id}/accept`,
  tournamentInvitationDecline: (id: number) => `/api/tournament-invitations/${id}/decline`,
  tournamentInvitationCancel: (id: number) => `/api/tournament-invitations/${id}/cancel`,
  teamRatings: (teamId: number) => `/api/ratings/teams/${teamId}`,
  teamRatingHistory: (teamId: number) => `/api/ratings/teams/${teamId}/history`,
  playerRatings: (playerId: number) => `/api/ratings/players/${playerId}`,
  playerRatingHistory: (playerId: number) => `/api/ratings/players/${playerId}/history`,
  matchRatingDelta: (matchId: number) => `/api/ratings/matches/${matchId}`
};
